services:
  ComfyUI:
    container_name: ComfyUI
    image: comfy-ui-custom:latest
    isolation: process
    restart: unless-stopped
    ports:
      - 8188:8188
    volumes:
      - 'D:\comfy\models:C:\app\ComfyUI\models'
      - 'D:\comfy\custom_nodes:C:\app\ComfyUI\custom_nodes'
    devices:
      - class/5B45201D-F2F2-4F3B-85BB-30FF1F953599     # Passing GPU, Dont Change. Delete this block if you dont want to use GPU